name: build-test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  GO_VERSION: 1.16

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build and test the application
        run: |
          make docker-build
