name: build-publish
on:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

jobs:
  build-publish:
    name: build-publish
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: ghcr.io
      GITHUB_ORGANIZATION: levivannoort #topicuskeyhub
      APPLICATION_NAME: keyhub-vault-operator
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: build-container-image
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.GITHUB_ORGANIZATION }}/${{ env.APPLICATION_NAME }}:${{ github.GITHUB_REF }} -t ${{ env.CONTAINER_REGISTRY }}/${{ env.GITHUB_ORGANIZATION }}/${{ env.APPLICATION_NAME }}:latest .

      - name: login-to-ghcr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push-container-image
        run: docker push --all-tags ${{ env.CONTAINER_REGISTRY }}/${{ env.GITHUB_ORGANIZATION }}/${{ env.APPLICATION_NAME }}
