name: test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

env:
  GO_VERSION: 1.16
  KUBEBUILDER_VERSION: 2.3.1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup kubebuilder
        run: |
          curl -sS -L -o kubebuilder.tar.gz https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${{ env.KUBEBUILDER_VERSION }}/kubebuilder_${{ env.KUBEBUILDER_VERSION }}_linux_amd64.tar.gz && \
          tar xvf kubebuilder.tar.gz && \
          mv kubebuilder_${{ env.KUBEBUILDER_VERSION }}_linux_amd64 ~/.local/kubebuilder && \
          chmod +x ~/.local/kubebuilder/bin/*

      - name: Run tests
        run: |
          make test
