name: test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

env:
  GO_VERSION: 1.16

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: |
          make test
