name: test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # to-do: test

      # to-do: report test coverage
